### PR TITLE
added the logo, font and the font colors

### PR DESCRIPTION
**Pull request by samuel-jarvis**
My first PR.

I designed a Logo and added it to the files.

I also added the fonts to the index files and the primary colours to the styles.

### CODE REVIEW

**Comment by thekingslee** [comment]
LGTM

**Comment by thekingslee** [comment]
Your commit messages can improve. 
I recommend this article https://chiamakaikeanyi.dev/how-to-write-good-git-commit-messages/

**Comment by thekingslee** [comment]
> Your commit messages can improve. I recommend this article https://chiamakaikeanyi.dev/how-to-write-good-git-commit-messages/

I hope you don't mind me dropping stuff like this on your PR once in a while

**Comment by samuel-jarvis** [comment]
I really don't mind. I appreciate these remarks. I'm learning.
Thanks

**Pull request merged**
